### ISSUE TITLE
关于 Mod 的原创性

### ISSUE THREAD

**Issue by limengzestudio** [Jack253-png/More-Armor-Tools-for-1.18---Minecraft-Mod#1]
你这个mod...
skid别人的是吧
或是 mcreator 创建的

**Comment by Jack253-png** [comment]
logger.info("Now Time:"+new Date().toString());
int max = (int) (Runtime.getRuntime().maxMemory() / 1024 / 1024);
int total = (int) (Runtime.getRuntime().totalMemory() / 1024 / 1024);
logger.info("Max Memory:"+max+"MB");
logger.info("Total Memory:"+total+"MB");
logger.info("Run on OS:"+ System.getProperty("os.name"));
这段代码用于区分原创代码

**Comment by limengzestudio** [comment]
这些代码压根没法区分是否原创，而且你一个人能做出这么多版本的Mod?
PowerMod我们当时10个人做了1年半才做好单版本，MagicOriginCore写了大概半年，还是半成品

**Comment by Jack253-png** [comment]
谁这种mod会在fabric上做，还有你看看贴图的品质是不是盗来的



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月18日 11:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [Jack253-png/More-Armor-Tools-for-1.18---Minecraft-Mod] 关于 Mod 的原创性 (Issue #1) |

你这个mod...
skid别人的是吧
或是 mcreator 创建的
